### PR TITLE
Richard Di Natale has replaced Christine Milne as parliamentary leader of the Greens.

### PR DESCRIPTION
**Pull request by claudinec**

### CODE REVIEW

**Comment by davekinkead** [comment]
Excellent!

**Comment by henare** [comment]
Seeing this PR reminded me that we recently updated OA.org with John Faulkner's replacement. See https://github.com/openaustralia/openaustralia-parser/commit/84989f9e83375cb6e618a19f88db55dbecd19498 and https://github.com/openaustralia/openaustralia-parser/commit/bc0dc39562328a5e14c2a3a253b675b4495817a5

**Comment by claudinec** [comment]
Hi and thanks! I've been looking into the feasibility of a Writetothem/Write-it feature for a client and found this via the openaustralia list. Just getting a sense of the various contact-data projects at this stage.

**Comment by davekinkead** [comment]
Barton is a bit out of date at the moment.  If I could find the time, I'd love to put more effort into create more atom & composable open gov libraries.

**Pull request merged**
